// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/PhilSuslov/homework/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// InventoryRepository is an autogenerated mock type for the InventoryRepository type
type InventoryRepository struct {
	mock.Mock
}

// GetPart provides a mock function with given fields: ctx, req
func (_m *InventoryRepository) GetPart(ctx context.Context, req model.GetPartRequest) (model.GetPartResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 model.GetPartResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetPartRequest) (model.GetPartResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetPartRequest) model.GetPartResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.GetPartResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetPartRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListParts provides a mock function with given fields: ctx, req
func (_m *InventoryRepository) ListParts(ctx context.Context, req model.ListPartsRequest) (model.ListPartsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 model.ListPartsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ListPartsRequest) (model.ListPartsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ListPartsRequest) model.ListPartsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.ListPartsResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ListPartsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInventoryRepository creates a new instance of InventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRepository {
	mock := &InventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
