// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	payment_v1 "github.com/PhilSuslov/homework/shared/pkg/proto/payment/v1"
	mock "github.com/stretchr/testify/mock"
)

// PayService is an autogenerated mock type for the PayService type
type PayService struct {
	mock.Mock
}

// PayOrder provides a mock function with given fields: ctx, req
func (_m *PayService) PayOrder(ctx context.Context, req *payment_v1.PayOrderRequest) (*payment_v1.PayOrderResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *payment_v1.PayOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment_v1.PayOrderRequest) (*payment_v1.PayOrderResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *payment_v1.PayOrderRequest) *payment_v1.PayOrderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment_v1.PayOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *payment_v1.PayOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPayService creates a new instance of PayService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPayService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PayService {
	mock := &PayService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
