// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/user.proto

package common_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сессия кэша в Redis
type User struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserUuid            string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`                                  // UUID пользователя
	Login               string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`                                                        // Логин пользователя
	Password            string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`                                                  // Пароль пользователя
	Email               string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`                                                        // Email пользователя
	NotificationMethods []*NotificationMethods `protobuf:"bytes,5,rep,name=notification_methods,json=notificationMethods,proto3" json:"notification_methods,omitempty"` // Список каналов уведомлений пользователя
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetNotificationMethods() []*NotificationMethods {
	if x != nil {
		return x.NotificationMethods
	}
	return nil
}

// Каналы уведомления пользователя
type NotificationMethods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  *string                `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3,oneof" json:"provider_name,omitempty"` // Имя провайдера (например, telegram, email, push)
	Target        *string                `protobuf:"bytes,2,opt,name=target,proto3,oneof" json:"target,omitempty"`                                 // Адрес получателя — email, ID чата и т.д.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationMethods) Reset() {
	*x = NotificationMethods{}
	mi := &file_common_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMethods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMethods) ProtoMessage() {}

func (x *NotificationMethods) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMethods.ProtoReflect.Descriptor instead.
func (*NotificationMethods) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationMethods) GetProviderName() string {
	if x != nil && x.ProviderName != nil {
		return *x.ProviderName
	}
	return ""
}

func (x *NotificationMethods) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

// Запрос на получение юзера
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"` // UUID пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_common_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// Ответ на получение пользователя
type GetUserResponser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponser) Reset() {
	*x = GetUserResponser{}
	mi := &file_common_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponser) ProtoMessage() {}

func (x *GetUserResponser) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponser.ProtoReflect.Descriptor instead.
func (*GetUserResponser) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponser) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Запрос на регистрацию пользователя
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_common_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Ответ на регистрацию пользователя
type RegisterResponser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponser) Reset() {
	*x = RegisterResponser{}
	mi := &file_common_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponser) ProtoMessage() {}

func (x *RegisterResponser) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponser.ProtoReflect.Descriptor instead.
func (*RegisterResponser) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponser) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_common_v1_user_proto protoreflect.FileDescriptor

const file_common_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x14common/v1/user.proto\x12\tcommon.v1\"\xbe\x01\n" +
	"\x04User\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12Q\n" +
	"\x14notification_methods\x18\x05 \x03(\v2\x1e.common.v1.NotificationMethodsR\x13notificationMethods\"y\n" +
	"\x13NotificationMethods\x12(\n" +
	"\rprovider_name\x18\x01 \x01(\tH\x00R\fproviderName\x88\x01\x01\x12\x1b\n" +
	"\x06target\x18\x02 \x01(\tH\x01R\x06target\x88\x01\x01B\x10\n" +
	"\x0e_provider_nameB\t\n" +
	"\a_target\"-\n" +
	"\x0eGetUserRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"7\n" +
	"\x10GetUserResponser\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.common.v1.UserR\x04user\"6\n" +
	"\x0fRegisterRequest\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.common.v1.UserR\x04user\"'\n" +
	"\x11RegisterResponser\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid2\x96\x01\n" +
	"\vUserService\x12D\n" +
	"\bRegister\x12\x1a.common.v1.RegisterRequest\x1a\x1c.common.v1.RegisterResponser\x12A\n" +
	"\aGetUser\x12\x19.common.v1.GetUserRequest\x1a\x1b.common.v1.GetUserResponserBEZCgithub.com/PhilSuslov/homework/shared/pkg/proto/common/v1;common_v1b\x06proto3"

var (
	file_common_v1_user_proto_rawDescOnce sync.Once
	file_common_v1_user_proto_rawDescData []byte
)

func file_common_v1_user_proto_rawDescGZIP() []byte {
	file_common_v1_user_proto_rawDescOnce.Do(func() {
		file_common_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_user_proto_rawDesc), len(file_common_v1_user_proto_rawDesc)))
	})
	return file_common_v1_user_proto_rawDescData
}

var file_common_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_v1_user_proto_goTypes = []any{
	(*User)(nil),                // 0: common.v1.User
	(*NotificationMethods)(nil), // 1: common.v1.NotificationMethods
	(*GetUserRequest)(nil),      // 2: common.v1.GetUserRequest
	(*GetUserResponser)(nil),    // 3: common.v1.GetUserResponser
	(*RegisterRequest)(nil),     // 4: common.v1.RegisterRequest
	(*RegisterResponser)(nil),   // 5: common.v1.RegisterResponser
}
var file_common_v1_user_proto_depIdxs = []int32{
	1, // 0: common.v1.User.notification_methods:type_name -> common.v1.NotificationMethods
	0, // 1: common.v1.GetUserResponser.user:type_name -> common.v1.User
	0, // 2: common.v1.RegisterRequest.user:type_name -> common.v1.User
	4, // 3: common.v1.UserService.Register:input_type -> common.v1.RegisterRequest
	2, // 4: common.v1.UserService.GetUser:input_type -> common.v1.GetUserRequest
	5, // 5: common.v1.UserService.Register:output_type -> common.v1.RegisterResponser
	3, // 6: common.v1.UserService.GetUser:output_type -> common.v1.GetUserResponser
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_v1_user_proto_init() }
func file_common_v1_user_proto_init() {
	if File_common_v1_user_proto != nil {
		return
	}
	file_common_v1_user_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_user_proto_rawDesc), len(file_common_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_v1_user_proto_goTypes,
		DependencyIndexes: file_common_v1_user_proto_depIdxs,
		MessageInfos:      file_common_v1_user_proto_msgTypes,
	}.Build()
	File_common_v1_user_proto = out.File
	file_common_v1_user_proto_goTypes = nil
	file_common_v1_user_proto_depIdxs = nil
}
