// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/PhilSuslov/homework/order/internal/repository/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// CancelOrder provides a mock function with given fields: ctx, orderUUID
func (_m *OrderRepository) CancelOrder(ctx context.Context, orderUUID uuid.UUID) (*model.OrderDto, bool) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 *model.OrderDto
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.OrderDto, bool)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.OrderDto); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// CreateOrder provides a mock function with given fields: order
func (_m *OrderRepository) CreateOrder(order *model.OrderDto) {
	_m.Called(order)
}

// GetOrderByUUID provides a mock function with given fields: ctx, orderUUID
func (_m *OrderRepository) GetOrderByUUID(ctx context.Context, orderUUID uuid.UUID) (*model.OrderDto, bool) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUUID")
	}

	var r0 *model.OrderDto
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.OrderDto, bool)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.OrderDto); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// PayOrder provides a mock function with given fields: orderUUID, payUUID, paymentMethod
func (_m *OrderRepository) PayOrder(orderUUID uuid.UUID, payUUID uuid.UUID, paymentMethod string) (*string, error) {
	ret := _m.Called(orderUUID, payUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, string) (*string, error)); ok {
		return rf(orderUUID, payUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, string) *string); ok {
		r0 = rf(orderUUID, payUUID, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(orderUUID, payUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayOrderCreate provides a mock function with given fields: ctx, req, orderUUID
func (_m *OrderRepository) PayOrderCreate(ctx context.Context, req *model.PayOrderRequest, orderUUID uuid.UUID) (*model.OrderDto, bool) {
	ret := _m.Called(ctx, req, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for PayOrderCreate")
	}

	var r0 *model.OrderDto
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, *model.PayOrderRequest, uuid.UUID) (*model.OrderDto, bool)); ok {
		return rf(ctx, req, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.PayOrderRequest, uuid.UUID) *model.OrderDto); ok {
		r0 = rf(ctx, req, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.PayOrderRequest, uuid.UUID) bool); ok {
		r1 = rf(ctx, req, orderUUID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
