// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/PhilSuslov/homework/order/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// CancelOrder provides a mock function with given fields: ctx, orderUUID
func (_m *OrderService) CancelOrder(ctx context.Context, orderUUID uuid.UUID) error {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateOrder provides a mock function with given fields: ctx, request
func (_m *OrderService) CreateOrder(ctx context.Context, request *model.CreateOrderRequest) (model.CreateOrderResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 model.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateOrderRequest) (model.CreateOrderResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateOrderRequest) model.CreateOrderResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(model.CreateOrderResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreateOrderRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByUUID provides a mock function with given fields: ctx, orderUUID
func (_m *OrderService) GetOrderByUUID(ctx context.Context, orderUUID uuid.UUID) (*model.OrderDto, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUUID")
	}

	var r0 *model.OrderDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.OrderDto, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.OrderDto); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewError provides a mock function with given fields: ctx, err
func (_m *OrderService) NewError(ctx context.Context, err error) *model.GenericErrorStatusCode {
	ret := _m.Called(ctx, err)

	if len(ret) == 0 {
		panic("no return value specified for NewError")
	}

	var r0 *model.GenericErrorStatusCode
	if rf, ok := ret.Get(0).(func(context.Context, error) *model.GenericErrorStatusCode); ok {
		r0 = rf(ctx, err)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GenericErrorStatusCode)
		}
	}

	return r0
}

// PayOrder provides a mock function with given fields: ctx, req, orderUUID
func (_m *OrderService) PayOrder(ctx context.Context, req *model.PayOrderRequest, orderUUID uuid.UUID) (model.PayOrderResponse, error) {
	ret := _m.Called(ctx, req, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 model.PayOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PayOrderRequest, uuid.UUID) (model.PayOrderResponse, error)); ok {
		return rf(ctx, req, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.PayOrderRequest, uuid.UUID) model.PayOrderResponse); ok {
		r0 = rf(ctx, req, orderUUID)
	} else {
		r0 = ret.Get(0).(model.PayOrderResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.PayOrderRequest, uuid.UUID) error); ok {
		r1 = rf(ctx, req, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
